tst1={1,2,3,4,5}
tst2=tuple(tst1)
tst3=list(tst1)
tst4=dict(zip(tst1,tst1))  # define a dictionary where keys and values get the same providerb{tst1)
typ1=type(tst1)
typ2=type(tst2)
typ3=type(tst3)
typ4=type(tst4)
print("type 1:")
print(typ1)
print(tst1)
print("type 2 :")
print(typ2)
print("type 3 :")
print(typ3)
print(tst3)
print("type 4:")
print(typ4)
print(tst4)

# this is another way to display information

tst1={1,2,3,4,5}
tst2=tuple(tst1)
tst3=list(tst1)
tst4=dict(zip(tst1,tst1))
typ1=type(tst1)
typ2=type(tst2)
typ3=type(tst3)
typ4=type(tst4)
print("type 1:" + " " + str(typ1) + ":" + " " + str(tst1))
print(typ1)
print(tst1)
print("type 2 :" + " " + str(typ2) + ":" + " " + str(tst2))
print(typ2)
print("type 3 :" + " " + str(typ3) + ":" + " " + str(tst3))
print(typ3)
print(tst3)
print("type 4:" + " " + str(typ4) + ":" + " " + str(tst4))
print(typ4)
print(tst4)
